### ISSUE TITLE
slave vulnerable to DNSSEC amplification attack

### ISSUE THREAD

**Issue by nils-wisiol** [desec-io/desec-slave#1]
Our slave does not define any firewall rules that stop DNSSEC amplificationn attacks and leaves that task to the docker host. We should introduce a mitigation that ships with the slave image.

**Comment by peterthomassen** [comment]
This is currently not possible to do inside a docker container. `iptables` only works on the host. We should add a note in `README.md` pointing out that this is the host's responsibility, maybe along with an example.
